PerlinTerrain now destroys old MeshCollider before creating a new one.
MissingReferenceException: The object of type
In its current state Unity throws this error when you press "Regenerate"
but it doesn't seem to affect the process:
" 'MeshCollider' has been destroyed but you are still trying to access
it.
Your script should either check if it is null or you should not
destroy the object."